language: java
install: mvn install -DskipTests=true -Dgpg.skip=true
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
matrix:
  allow_failures:
    - jdk: openjdk6
  fast_finish: true
notifications:
  email:
    recipients:
      - apisupport@upwork.com
    on_failure: change
